import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";


import { TestProvider } from "../contexts/testContext";
import { ListActionProvider } from "../contexts/listActionContext";
import Header from "@/src/app/components/Header/Header";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
      <html lang="en">
      <body>
      <div className="container py-3">
        <main>
          <TestProvider>
            <ListActionProvider>
                <Header />
              {children}
            </ListActionProvider>
          </TestProvider>
        </main>
      </div>
      </body>
      </html>
  );
}
